spring:
  application:
    name: triplan
  config:
    import: optional:classpath:application-secret.yaml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 0k2Tkmcl2QH/4sGUyXnW2jQtZFi5c9ZtBPFCvf977ag=
